Backend Kotlin
sandokandias/grpc-web-research pull request #2
Opened 2021-05-11 13:03 UTC by antoniofilhozup

2021-05-13 12:46 UTC, sandokandias requested changes

2021-05-13 12:46 UTC, sandokandias commented on backend-kotlin/src/main/proto/payment.proto
> +syntax = "proto3";
you could use the proto file that is in the proto folder of the repo and remove this file

2021-05-13 12:48 UTC, sandokandias commented
you need to add the directive in the Makefile to generate the kotlin stubs

2021-05-18 13:55 UTC, antoniofilhozup commented on backend-kotlin/src/main/proto/payment.proto
> +syntax = "proto3";
Done, thanks @JoaoDanielRufino

2021-05-18 13:59 UTC, antoniofilhozup commented
In order to generate the stub files, just build the application with the command `./gradlew build`.

2021-05-18 17:45 UTC, sandokandias approved these changes

2021-05-18 17:45 UTC, merged